version: '3.9'

services:
  booking-core_app:
    container_name: 'booking-core_app'
    image: 'booking-core'
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://booking-core_db:5432/core_db
      DATABASE_USERNAME: core_user
      DATABASE_PASSWORD: core
    depends_on:
      - booking-core_db
  booking-core_db:
    container_name: 'booking-core_db'
    image: 'postgres:12'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
